### PR TITLE
Fix for error: writing 8 bytes into a region of size 4

### PR DESCRIPTION
**Pull request by faveoled**
The current code fails to compile on Ubuntu 24.04:
```
rsa.c: In function ‘RSA_verify’:
rsa.c:283:16: error: writing 8 bytes into a region of size 4 [-Werror=stringop-overflow=]
  283 |         buf[i] ^= *hash++;
      |                ^~
```
This PR isn't a proper fix but a way to get this issue more attention.

### CODE REVIEW

**Comment by 1vivy** [comment]
Use clang. `CC=clang make all`
